### ISSUE TITLE
Device edit button goes to the wrong place

### ISSUE THREAD

**Issue by danielquinn** [MycroftAI/selene-ui#40]
### Describe the bug

When you create/pair a device, you're given a small set of options to configure said device including values like which voice to use, its name, location, etc.  Once set, you used to be able to edit these values by going to [/devices](https://account.mycroft.ai/devices) and clicking the `[Edit]` button under your device.  However recently, clicking that button no longer directs you to a form where you can edit these values.  Instead, you're bounced to the "Advanced Settings" page where you're directed to read the documentation to further configure your device.

The stated documentation doesn't indicate how to change values like `location` for example, so there must be something missing... no?  I note that the URL for this page is `https://account.mycroft.ai/devices/<UUID>`, which makes me think this page was *supposed* to be dynamic based on that UUID, even though it's rendering a static page.

### To Reproduce

1. Go to home.mycroft.ai
2. Login
3. Select `Devices` from the top-right drop-down menu
4. Click the `[Edit]` button under any of your existing devices.

### Expected behavior

There used to be a form to update your devices basic values.  I assume that this is still supposed to be the case?  If not, some tips on how/where to change these values appropriately would be appreciated.

### Log files

None relevant.

### Environment

* **Device type**: Firefox Developer Edition v85 and Chromium 87 running in GNOME 3.38.2 on Arch Linux.  Devices include a Mark 1 and 3 Dockerised instances on 2 different Arch Linux machines
* **OS**: Arch Linux
* **Mycroft-core version**: `20.08` on all devices

### Additional context

I originally asked about this [on this Reddit post](https://www.reddit.com/r/Mycroftai/comments/kh3j3u/has_configuration_changed_or_is_there_a_bug_on/) as it wasn't clear where else to report strange behaviour on the website.  It might be a good idea to include a "report a bug on GitHub" link somewhere so people can feed you useful reports when necessary.

**Comment by chrisveilleux** [comment]
Thank you for reporting this issue, @danielquinn.  It has been addressed in a bug fix release yesterday.
